language: node_js
before_script:
  - git config --global user.email "lloyd.benson@gmail.com"
  - git config --global user.name "Travis-CI"
env:
  - CXX="g++-4.8"
node_js:
  - 4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
